spring:
  datasource:
    url: jdbc:h2:file:./database/testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

application:
  max-allowed-books: 2

logging:
  level:
    org.springframework: INFO
    ru.gb.myspringdemo: DEBUG