server:
  port: 8280
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: issuer-service
  cloud:
    compatibility-verifier:
      enabled: false
logging:
  level:
    root: DEBUG
